name: example
version: 1.0.0+1
publish_to: none
description: A new Flutter Project.
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  cupertino_icons: ^0.1.3
  url_launcher: any
  provider: any
  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
