name: example3
version: 1.0.0+1
publish_to: none
description: A Awesome Flutter Project
environment: 
  sdk: '>=2.7.0 <3.0.0'
dependencies: 
  http: any
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
